databases:
  - name: igeo-app
    databaseName: igeo-app
    user: igeo-app
    plan: free

services:
  - type: web
    plan: free
    name: igeo-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: igeo-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
